// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBcjufCmed3FVh4c5qbxjTa90Dt2SvF6NI',
    appId: '1:887317162810:web:6e9ef10fdfdb626d7c7e03',
    messagingSenderId: '887317162810',
    projectId: 'pothole-pinger',
    authDomain: 'pothole-pinger.firebaseapp.com',
    databaseURL: 'https://pothole-pinger-default-rtdb.firebaseio.com',
    storageBucket: 'pothole-pinger.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCWuIW9M9EEuw75QbXzEf4ACYThcZG-rbo',
    appId: '1:887317162810:android:de657aa1e5b519677c7e03',
    messagingSenderId: '887317162810',
    projectId: 'pothole-pinger',
    databaseURL: 'https://pothole-pinger-default-rtdb.firebaseio.com',
    storageBucket: 'pothole-pinger.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAErH7_3abMqzk6OHdBd8dBadePXEgIolA',
    appId: '1:887317162810:ios:1270583e6d298af17c7e03',
    messagingSenderId: '887317162810',
    projectId: 'pothole-pinger',
    databaseURL: 'https://pothole-pinger-default-rtdb.firebaseio.com',
    storageBucket: 'pothole-pinger.appspot.com',
    iosClientId: '887317162810-vf0uspfvk4ie9oamvhvuko4kv4of1tif.apps.googleusercontent.com',
    iosBundleId: 'com.example.gpsPinger',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAErH7_3abMqzk6OHdBd8dBadePXEgIolA',
    appId: '1:887317162810:ios:1270583e6d298af17c7e03',
    messagingSenderId: '887317162810',
    projectId: 'pothole-pinger',
    databaseURL: 'https://pothole-pinger-default-rtdb.firebaseio.com',
    storageBucket: 'pothole-pinger.appspot.com',
    iosClientId: '887317162810-vf0uspfvk4ie9oamvhvuko4kv4of1tif.apps.googleusercontent.com',
    iosBundleId: 'com.example.gpsPinger',
  );
}
